### ISSUE TITLE
Unable to install on debian

### ISSUE THREAD

**Issue by xtreme8000** [piqueserver/piqueserver#107]
[This is the installation log](https://pastebin.com/MznuEWXy), note that none of the other methods on the readme work. Idk whats wrong, I'm not a python master

**Comment by NotAFile** [comment]
Could you give some more info on the distribution, architecture etc? I see some unusual "InsecurePlatform" warnings popping up.

The error log suggests you should update your version of python, but googling "invalid command 'bdist_wheel'" reveals you likely have an old version of pip installed.

try `pip install --upgrade pip` to upgrade your pip to the latest version.

The Installation has been tested and should work fine, so I'm afraid the issue is probably on your end.

**Comment by xtreme8000** [comment]
Okay, so I uninstalled wheel and upgraded setuptools and it actually worked.

**Comment by NotAFile** [comment]
Awesome! great!
