### ISSUE TITLE
[Bug] Flying Player Hack

### ISSUE THREAD

**Issue by 0verk1ll** [piqueserver/piqueserver#431]
While playing Babel, an enemy player was flying around on blocks. New blocks were magically built in front of them and the blocks behind them fell apart on their own. They were moving to quickly to be shot down.

![flyingscreenshot](https://user-images.githubusercontent.com/22098433/50539906-13f42e80-0b80-11e9-83ed-6b3afb2a9e06.png)

**Comment by yvt** [comment]
Probably there's a script installed on the server that makes such a thing possible under some circumstances that you are not aware of (e.g., limited to admins and/or guards). The server usually rejects building a mid-air block, unless it was forced by some server scripts.

**Comment by NotAFile** [comment]
Yes, this should be prevented by the server. I know there have been similar scripts in the past. What server is this on?

**Comment by 0verk1ll** [comment]
Unfortunately, I don't remember which server it was on.
The weird thing is that my friend and I were playing together. We tried to votekick a griefer and then a little while later, we were banned from the server for no reason. It seemed like everyone was cheating on the server, but maybe we just didn't understand the game mechanics for that particular server.

**Comment by yvt** [comment]
I doubt this issue should still be open, but in case you are interested in figuring out which server you were in, you can find all the logs in the config directory.
https://github.com/yvt/openspades/wiki/User-Resource-Directory
Look for a banner message like this:
```
Thu Dec 27 22:21:35 2018 ------ World Loaded ------
Thu Dec 27 22:21:36 2018 Welcome to aloha.pk tower of babel
```

**Comment by damienflament** [comment]
@0verk1ll  This issue is closed, but I just want to point out that it is not a bug. I experimented the same problem on a the Polski server which mainly run Hallway based custom maps.

In the past, the 'fly' command was enabled for everyone. But today, there is just a custom script which gives you full ammo when you place a block (not everyone is aware of it, you have to try it to check if it is enabled on your current server).

I also saw some players who enabled the god mode (just for them) and started griefing opponents base. Some of them also use the 'fly' which allow them to fly by jumping in air.

They also use some commands which allow them to build blocks structures really quickly (those commands are usually available only on build servers).

Don't even try to complain about it on those servers. Just leave if you are bored. Those players are just privileged players (moderators or admins) who don't care about fair-play.
