### ISSUE TITLE
Refactor netcode to always use UDP

### ISSUE THREAD

**Issue by Conticop** [piqueserver/piqueserver#601]
**Is your feature request related to a problem?**
Yes. Known as *desync*.

**Describe the solution you'd like**
As the title suggests.
The main goal is to improve netcode as a whole, stop mixing TCP/UDP packets simultaneously(!!!), and to fix *desync* along the way.
This is **not** an easy task. Also I would assume so, it *may* require changes on both client and server (rip vanilla).

**Additional context**
I don't know much about pyenet/ENet, but seeing this LoC made me laugh (default to "reliable"):
`def broadcast_contained(self, contained, unsequenced=False`
TCP (reliable/sequenced) is the worst thing you can do to a real-time multiplayer game.
Mixing TCP and UDP (on the same port) is a recipe for **catastrophe** (mainly resulting in a *desync* issue).
Ask any multiplayer networking expert, and they will confirm the above claim. (AAA games use a custom UDP and UDP only for server<->client protocol.)
[...]
I wish I could post the video about *desync* I had experienced (on N-S) before, the video has passed away, anyways I will try to make a new recording soon.
For now I will just paste a quote of my comment (which can be found on N-S discord) when I was being accused for "noclipping":
![comment](https://cdn.discordapp.com/attachments/676483344518742026/744184430846804068/unknown.png)
(I was using openspades as my client, not that it really matters tho. P3P3 was an admin who were spectating me ingame when that happened.)

----

There is also a decent blogpost about multiplayer networking, [click here](https://gafferongames.com/categories/game-networking/) and read [`UDP vs. TCP`](https://gafferongames.com/post/udp_vs_tcp/) post.

**Comment by SkyDiverCool** [comment]
### The idea of possibly dropping Vanilla is borderline blasphemous.

Also the screenshot is from nearly a year ago and **(at least to my knowledge)** there have not been other cases documented of this happening since.

Also I do not believe the use of UDP matters to the same degree in aos compared to other newer games because in aos all of the movement and shooting is happening on the server side so even if a desync event is happening it doesnt provide an advantage over other players and cannot be abused(in your case information could be gathered about players behind walls but its so rare its just simpler to cheat).

**Comment by NotAFile** [comment]
Hi. I'm not sure how to say this politely Conticop but you have absolutely zero idea what you are talking about.

Enet and hence pique already exclusively use UDP for server client communication. There are absolutely some smaller optimizations that can be made in how pique and the clients use the queuing and reliability features enet provides (that doesn't even require breaking compatability). But that won't change the fact that the AoS protocol is just not well designed which the primary cause of issues.
