### ISSUE TITLE
Map's apply_script version never gets called

### ISSUE THREAD

**Issue by dany-on-demand** [piqueserver/piqueserver#781]
https://github.com/piqueserver/piqueserver/blob/87c9f09141209ca2ab5fd8e2bd28a4dc62f332c4/piqueserver/map.py#L123

Unlikely this is a regression? Guessing it was just never implemented fully

https://github.com/piqueserver/piqueserver/blob/87c9f09141209ca2ab5fd8e2bd28a4dc62f332c4/piqueserver/extensions.py#L147
The only place where apply_script gets called
It itself gets only called in server.py run() and only on files game_modes and scripts/ folder
I'm pretty sure the fix is to simply to call apply_script in the same manner as in run.py whenever the map changes/loads

Repro (not sure if the func is correct since I never got it to run) `Test.txt`:
```
name = 'Test'
version = '1.0'
author = 'Dany0'
description = 'Chungus.'

print("inside script for Test")

def apply_script(protocol, connection, config):
    print("Applying script for Test")
    class TestConnect(connection):
         def on_spawn(self, pos):
            print("entered on_spawn")
            return connection.on_spawn(self, pos)
    return protocol, TestConnect

```

stdout:

```
2024-02-29T00:02:27+0100 [stdout#info] inside script for Test
2024-02-29T00:02:27+0100 [piqueserver.map#info] Loading map 'Test'...

... nothing after
```

Expected:
> inside script for Test
> Applying script for Test
> entered on_spawn (when player spawns)

**Comment by utf-4096** [comment]
You're right, it seems like this was a planned feature that was never finished since we never actually call `<map instance>.apply_script(...)`.
IMO, map config files should have as little scripting as possible. If you need anything more complex than setting the player / tent / intel spawn positions, you should make a script or gamemode instead.

I think our future goal is to have a safe, non-scripted but extensible map format, so adding such a feature right now would not make much sense.

Unless there's a use case I can't think of right now, I'm probably gonna remove this `apply_script()` code entirely to prevent confusion.
