### ISSUE TITLE
Replace non-working airstrike.py with working airstrike2.py

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#80]
`airstrike.py` does not currently work.

`airstrike2.py` is a much improved version, it is however not currently included. IMO, it should replace `aimbot.py`

**Comment by 1AmYF** [comment]
Additional info:
airstrike.py does not inflict any damage to enemy players when using it with current piqueserver or pyspades/pysnip (no exception/error thrown). Worked however when i tested it with some other (possibly older) pyspades builds.
airstrike2.py does not have this problem, but has a different approach - instead of something like `/airstrike B4` you need to scope at a ground and press v to launch airstrike there. While i personally prefer this one, i have seen some people struggling with the instructions on how to apply their airstrike. Another difference is, with airstrike.py you lose your earned airstrike if you die before using it, in airstrike2.py you can still use it after respawning.

**Comment by feikname** [comment]
Fixed in #83
