### ISSUE TITLE
Find a good way to do central plugin configuration

### ISSUE THREAD

**Issue by NotAFile** [piqueserver/piqueserver#82]
Currently, plugins rely on directly editing the source code for configuration. Ideally, this would be managed centrally.

One option would be to add a module for this that all plugins can use. It would automatically handle parsing and creating the config file and passing the data to the script.

**Comment by damienflament** [comment]
Currently, the scripts have access to the main configuration. Some use it (think about the map extensions). All should use it.

A module dedicated to this task may push scripts authors to use the configuration instead of relying on variable value modification.

Moreover, this module can provide configuration abstraction and give access to all the configuration values for reading, but only to a subset of them (located under a "namespace" implemented by an object in the root configuration object) for writing. It should prevent conflicts between the scripts.

**Comment by damienflament** [comment]
Related to my previous comment:

As the map configuration file (`mapname.txt`) is also reachable, the configuration module should provide the save features than for the main configuration file. Some scripts (like _arena_) rely on the map configuration.

**Comment by NotAFile** [comment]
Since this already exists and the config rewrite will fix this too, I'll close this
